### ISSUE TITLE
You can make this train more quickly.

### ISSUE THREAD

**Issue by gavinpotter** [cair/TsetlinMachine#12]
You can make this train more quickly.  We've noticed that  the calculate_clause_output in the multiclass machine calculates all the classes when training.  However, you only need to calculate the positive and negative classes for each point.  So, if you have 10 classes, the calculate_clause_output performs 10/2 = 5 times as many calculations as necessary.  As this is one of the two long running methods a reasonably substantial saving in time can be made.  The change is very easy.  The results are identical.

Thanks for writing such clear code.  We've created our own implementation based on your code using numba rather than cython which was very easy.  It looks a very interesting technique, and, so far, we've managed to replicate all of your results that we've tried.

Mnist is our 'goto' dataset for initial assessments of new techniques. However, we want to do our own port to the gpu before running it.  If it passes that test, we will add it to our base techniques.

I think your papers slightly under sell the interpretability benefit of the technique.  What we hadn't realised until we tried it, is that any point may only trigger a small number of clauses even if there are a large number of clauses per class.  This is different to a random forest (say) where every point triggers a path down every decision tree making interpretability much harder.

**Comment by olegranmo** [comment]
Thanks for these keen observations, @gavinpotter!
