### ISSUE TITLE
Confusion about type 1 feedback

### ISSUE THREAD

**Issue by apaz-cli** [cair/TsetlinMachine#13]
In an attempt to understand, and perhaps try some things out, I implemented a much faster TM in C++. Problem is, it doesn't work. I thought that I implemented it exactly as the paper described, but obviously not.

The first thing that I did was implement the Type 1 feedback table.

```c
static inline float
t1feedback_table(bool clause, bool literal, bool include) {
    static constexpr float type1rewards[] = {(1 / S), ((S - 1) / S)};
    bool NA = literal | !clause | !include;
    return type1rewards[(clause & literal)] * NA;
}

static inline TsetlinAutomaton
t1feedback_is_penalty(bool clause, bool literal, bool include) {
    TsetlinAutomaton options[] = {(TsetlinAutomaton)1, (TsetlinAutomaton)-1};
    return options[((clause & literal) ^ include)];
}

// Takes in previous state and returns the next state
inline TsetlinAutomaton
calc_t1_feedback(TsetlinAutomaton prev_state, bool clause_output, bool literal, bool include) {
    // Sample from the table. Reward is +1, penalty is -1, and no change is 0.
    TsetlinAutomaton t1_reward = rand_bernoulli(t1feedback_table(clause_output, literal, include)) *
                                                     t1feedback_is_penalty(clause_output, literal, include);

    // If the automaton is positive, a reward adds, and a penalty subtracts.
    // If the automaton is negative, a reward subtracts, and a penalty adds.
    static constexpr TsetlinAutomaton direction[] = {(TsetlinAutomaton)-1,
                                                                               (TsetlinAutomaton)1};
    t1_reward *= direction[include];

    // Apply the feedback to the current state and return the new state.
    return saturated_add(prev_state, t1_reward);
}
```

The implementation above is what the paper does, as I interpreted it. Doing it this way is also a whole lot faster than the reference implementations. However, something is clearly wrong, because it's not working. So I looked into the reference implementations.

To illustrate my confusion with the section of the code, I have created the following image.
![Tsetlin T1 Training Highlighted](https://user-images.githubusercontent.com/47389403/129143103-3084936e-ab85-40b9-ad91-825a141328e4.png)

The first part, circled in red, makes perfect sense to me. It does not depend on the literal, so the literal is not checked. The current state is also not checked, because subtracting is a reward when excluding, and a penalty when including.

The second part, circled in green, I'm not sure what's going on. I can definitely see many of the same patterns, but I don't think it matches the table. Indeed you're checking the literal, but I'm not sure how you can get around checking whether the automaton is including or excluding. I thought that NAs had to be dealt with.

Thanks,
apaz

**Comment by olegranmo** [comment]
Hi Apaz, the reason for the difference is that the code has been optimized. The end result is exactly the same. The version implemented is explained algorithmically here in Chapter 1: https://tsetlinmachine.org. Hope the information is useful!

**Comment by ivanstepanovftw** [comment]
In Type I(a) feedback (Type I feedback, first rule with condition $C_j(X) = 1$ and $l_k = 1$), how penalty can ever occur?

Clause Output $C_j(X)$ is 1.
Literal Value $l_k$ is 1.
Inclusion and Exclusion of literal controlled by automata state, i.e. non-negative state (0 and more) is inclusion, negative (-1 and less) is exclusion of target literal, so `include = automata_state >= 0`.
Literal is defined as a set of included complemented inputs.
So, Literal Value `l_k = input_complement AND include`.

It is confusing. Can we have such configuration where automata state is excluded and literal evaluated to 1?

I understand that it is possible for literal value $l_k$ to be 0 and still evaluate clause $C_j(X)$ to 1, in 1 case - when training and clause is empty. But I cannot understand that case with Type 1.

**Comment by DarshanaAbeyrathna** [comment]
Tsetlin Machine (TM) considers both original input values and their negations to be included in clauses. For instance, 
if the original input $X = [x_1, x_2, x_3] = [1, 0, 1]$, the TM takes it as $[x_1, -x_1, x_2, -x_2, x_3, -x_3] = [l_1, l_2, l_3, l_4, l_5, l_6] = [1, 0, 0, 1, 1, 0]$.

In the code, an automaton has `2 * number_of_states` states. States from 0 to `number_of_states` decide to exclude the literal while states from `number_of_states + 1` decide to include the corresponding literal. 

Now think of a situation where the team of automata in $C_j$ decides to include $l_1$ and $l_5$ in the clause. In other words, the current state of the automata which represent literal $l_1$ and $l_5$ is higher than `number_of_states `. Then $C_{j}(X)$ is 1.

**Comment by DarshanaAbeyrathna** [comment]
Tsetlin Machine (TM) considers both the original input values and their negations when forming clauses. For instance, if the original input is:

$X = [x_1, x_2, x_3] = [1, 0, 1]$

the TM expands it to:

$[x_1, -x_1, x_2, -x_2, x_3, -x_3] = [l_1, l_2, l_3, l_4, l_5, l_6] = [1, 0, 0, 1, 1, 0]$.

In the code, each automaton has `2 * number_of_states` states. States from `0` to `number_of_states` decide to exclude the literal from the clause, while states from `number_of_states + 1` to `2 * number_of_states` decide to include the corresponding literal in the clause.

Now, consider a situation where the team of automata in $C_j$ decides to include $l_1$ and $l_5$ in the clause. In other words, the current states of the automata representing $l_1$ and $l_5$ in $C_j$ are higher than `number_of_states`. Hence, $C_j(X) = 1$.

When updating the automata states (assuming $C_j$ receives Type I feedback), the automaton representing $l_4$ literal receives a penalty since $l_4 = 1$ but is not included in $C_j$.

Hope this helps!

**Comment by ivanstepanovftw** [comment]
Hello @DarshanaAbeyrathna. I am trying to make NumPy port, but my solution does not converge. You helped me prevously, so I thought maybe you can spot the problem in vectorized code? See #16.
