### ISSUE TITLE
Sharing: Tsetline machine implementation based on tensor operations

### ISSUE THREAD

**Issue by fwaris** [cair/TsetlinMachine#14]
Please see: https://github.com/fwaris/FsTsetlin

(Still very much WIP)

The core of the Tsetlin machine is implemented using tensor operation (which can be parallelized).

The front-end language is [F#](https://fsharp.org/) (.Net) but it uses the tensor library underpinning [PyTorch](https://pytorch.org/) (via [TorchSharp](https://github.com/dotnet/TorchSharp))

Trains and predicts on GPU/CPU.

[edited]
Have to say the original Tsetlin machine paper is very well written. I wrote almost the entire code just from the paper.

**Comment by olegranmo** [comment]
Looks very interesting and thanks for the kind feedback on the paper! Look forward to trying it out :-)

**Comment by fwaris** [comment]
did some quick tests with the "noisy xor" dataset to compare CPU vs. GPU performance. CPU is faster with 10 clauses (per class). As clauses are increased steadily to 1000, CPU performance degrades quickly while GPU performance remains quite steady. This is not exhaustive testing but shows that system is working as intended.
