### ISSUE TITLE
Handling of missing data

### ISSUE THREAD

**Issue by WojciechMigda** [cair/TsetlinMachine#4]
Tsetlin Machine framework seems to be naturally suited for handling of datasets with occurences of missing data. Is handling of missing data something you have already thought about and we will read about such formal approach in any of the upcoming papers? Do you have thoughts you could share here, for instance?

**Comment by olegranmo** [comment]
Dear @WojciechMigda, thanks a lot for this interesting observation. Investigating the ability of the Tsetlin Machine to handle missing data would be very interesting. We have not at this moment worked on this. One simple approach would be to ignore the missing data when calculating the output of a clause, and then skip updating the affected Tsetlin Automata. How this would affect convergence is presently unknown to us.  I definitively encourage exploring this further.
