### ISSUE TITLE
clause_sign second dimension is too big?

### ISSUE THREAD

**Issue by WojciechMigda** [cair/TsetlinMachine#5]
Can you please confirm that the second dimension of `clause_sign` matrix should have its second dimension set to `number_of_clauses / number_of_classes`?

https://github.com/cair/TsetlinMachine/blob/9bfdac2b22d49c0535843fe551ccda1620661e91/MultiClassTsetlinMachine.pyx#L75

**Comment by olegranmo** [comment]
Confirmed! Good catch.
