### ISSUE TITLE
Help request to make a reccurent Tsetlin machine

### ISSUE THREAD

**Issue by electricmomo** [cair/TsetlinMachine#6]
Hi,

After reading the paper about introducing the Tsetlin machine, I am trying to make a recurrent network and train it. But I am still a newbie here :-).

Would you mind adding an simple example of recurrent Tseltin machine applied to XOR problem with the training code?

THanks

**Comment by olegranmo** [comment]
Hi @electricmomo! Thanks for getting in touch. We are currently working on the recurrent Tsetlin Machine. However, the Multilayer Tsetlin Machine will most likely be published first. Will let you know as soon as the paper is ready. With best wishes, Ole-Christoffer

O
