### ISSUE TITLE
Typ II feedback implementation

### ISSUE THREAD

**Issue by WojciechMigda** [cair/TsetlinMachine#7]
Hello,

I have a question regarding Type II feedback Multiclass TM code.
We have:
```
action_include = self.action(self.ta_state[j,k,0])
action_include_negated = self.action(self.ta_state[j,k,1])

if X[k] == 0:
	if action_include == 0 and self.ta_state[j,k,0] < self.number_of_states*2:
		self.ta_state[j,k,0] += 1
elif X[k] == 1:
	if action_include_negated == 0 and self.ta_state[j,k,1] < self.number_of_states*2:
		self.ta_state[j,k,1] += 1
```

since `action`  returns 0 iff its argument is less than `number_of_states`
```
cdef int action(self, int state):
	if state <= self.number_of_states:
		return 0
	else:
		return 1
```
it follows that right hand parts of conjunctions used as expressions to `if` statements above will always evaluate to true. Hence, the above simplifies to:
```
if X[k] == 0:
	if action_include == 0:
		self.ta_state[j,k,0] += 1
elif X[k] == 1:
	if action_include_negated == 0:
		self.ta_state[j,k,1] += 1
```
Is that correct or I am missing something?
Thanks.

**Comment by olegranmo** [comment]
Dear Wojciech Migda,

Thanks for your fine observation. You are of course right.

All the best!
